version: '3.3'

services:
  autocompleteapp:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules/
    ports:
      - '80:80'